version: '3.2'

services:
  smtp-sink:
    container_name: smtp-sink
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./tmp/mail:/tmp/mail
    ports:
      - 8025:25
